name: framapagen
favicon: null
layout_spectrum: 0.6508349359501153
typography_spectrum: 0.8097427138127387
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5268407207913697
  lightness: 0.17693799664266407
  saturation: 0.1094700456596911
  rhythmicContrast: 0.33165156398899853
purpose: []
